// <auto-generated />
using System;
using GiftAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GiftAPI.Migrations
{
    [DbContext(typeof(Contex))]
    [Migration("20230904060723_student")]
    partial class student
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GiftAPI.lib.Model.Course", b =>
                {
                    b.Property<int>("courseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("studentid")
                        .HasColumnType("int");

                    b.HasKey("courseid");

                    b.HasIndex("studentid");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("GiftAPI.lib.Model.Student", b =>
                {
                    b.Property<int>("studentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Mobilenumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.HasKey("studentid");

                    b.ToTable("StudentRegistration");
                });

            modelBuilder.Entity("GiftAPI.lib.Model.Course", b =>
                {
                    b.HasOne("GiftAPI.lib.Model.Student", null)
                        .WithMany("CourcesBE")
                        .HasForeignKey("studentid");
                });

            modelBuilder.Entity("GiftAPI.lib.Model.Student", b =>
                {
                    b.Navigation("CourcesBE");
                });
#pragma warning restore 612, 618
        }
    }
}
